### ISSUE TITLE
I cant compile

### ISSUE THREAD

**Issue by MeFFoS** [IstuntmanI/streamer-plugin-sampgdk-invoke#1]
I cant compile project,because havent function. It's only declare. `Error LNK2019`:
```cpp
bool OnDynamicObjectMoved( int objectid );
bool OnPlayerEditDynamicObject( int playerid, int objectid, int response, float x, float y, float z, float rx, float ry, float rz );
bool OnPlayerSelectDynamicObject( int playerid, int objectid, int modelid, float x, float y, float z );
bool OnPlayerShootDynamicObject( int playerid, int weaponid, int objectid, float x, float y, float z );
bool OnPlayerPickUpDynamicPickup( int playerid, int pickupid );
bool OnPlayerEnterDynamicCP( int playerid, int checkpointid );
bool OnPlayerLeaveDynamicCP( int playerid, int checkpointid );
bool OnPlayerEnterDynamicRaceCP( int playerid, int checkpointid );
bool OnPlayerLeaveDynamicRaceCP( int playerid, int checkpointid );
bool OnPlayerEnterDynamicArea( int playerid, int areaid );
bool OnPlayerLeaveDynamicArea( int playerid, int areaid );
bool OnPlayerGiveDamageDynamicActor( int playerid, int actorid, float amount, int weaponid, int bodypart );
bool OnDynamicActorStreamIn( int actorid, int forplayerid );
bool OnDynamicActorStreamOut( int actorid, int forplayerid );
bool Streamer_OnItemStreamIn( int type, int id );
bool Streamer_OnItemStreamOut( int type, int id );
bool Streamer_OnPluginError( char error[ ] );
```

**Comment by IstuntmanI** [comment]
See commit https://github.com/IstuntmanI/samp-streamer-plugin-sampgdk-invoke/commit/e018d5255addb1fda91c103fcda6d52b429910dd, it should make things clearer to you. Reply here if you solved it or if you have any additional problem.

**Comment by MeFFoS** [comment]
thank u.

**Comment by MeFFoS** [comment]
sorry,i dont know how contact with u, but can i do same for mysql plugin?because mysqlconn dont work on linux or it so hard for compile.

**Comment by IstuntmanI** [comment]
You are welcome, thanks for reporting.

I tried doing the same for MySQL plugin but it isn't working, I had to integrate it with my plugin (I had to cut it down a lot) because invoking MySQL Plugin functions in this way crashed the server a lot (most of the crashes came from the log-core). The MySQL plugin uses too many AMX functions and they aren't really valid from this plugin, for some reason. That plugin was the biggest problem when I migrated my server to C++ with sampGDK.

**Comment by MeFFoS** [comment]
maybe you could share your solution for the mysql?maybe create lib.I think that the mysql is a big problem for beginners who want to write a mod on c++. example, im can use mysqlcon++,but only in windows.

**Comment by IstuntmanI** [comment]
There are tons of C++ ways to implement MySQL in your plugin. You can search for them. I can't really share the solution, as I made it only for my gamemode and it has code that wouldn't be compatible with every plugin. (also, I can't provide a .lib, I integrated it directly in my plugin, in the same project)

**Comment by MeFFoS** [comment]
okay,thank u very much.
