### ISSUE TITLE
Callbacks

### ISSUE THREAD

**Issue by MeFFoS** [IstuntmanI/streamer-plugin-sampgdk-invoke#2]
Hello again. Can you help me with callbacks? I create Rectangle.
```cpp
zone = Plugins::Streamer::Area::CreateRectangle(1827.1022f, -1874.2893f, 1810.5925f, -1857.8458f);
```
and `OnPublicCall` dont call. what need to do more? `Plugins::Streamer::Object::Create` is work.
```cpp
PLUGIN_EXPORT bool PLUGIN_CALL OnPublicCall(AMX * amx, const char * name, cell * params, cell * retval)
{
	sampgdk::logprintf(name);
	std::string lName = std::string(name);
	if (lName == "OnDynamicObjectMoved") { return OnDynamicObjectMoved(static_cast< int >(params[1])); } // ( int objectid ) .......
}
```

**Comment by IstuntmanI** [comment]
Please take a look on [GitHub's markdown](https://guides.github.com/features/mastering-markdown/) and try to make your issues to look better in the future. At least look at the code of your post now, as I edited it for you.

You didn't specify what you want to be called. When you are using that function it isn't calling any callback. If you want `OnPlayerEnterDynamicArea` to be called then it should work. It does for me. Maybe you weren't actually in that area if you tested exactly that callback. Make sure that everything is alright.

**Comment by MeFFoS** [comment]
Need add in main.def OnPublicCall .

**Comment by IstuntmanI** [comment]
Thanks for creating this issue. Commits https://github.com/IstuntmanI/samp-streamer-plugin-sampgdk-invoke/commit/c1f8c99af99e3a9ae0b7829df23df8db4b6a4e4b and https://github.com/IstuntmanI/samp-streamer-plugin-sampgdk-invoke/commit/582a0026802b22f62dddcdca559cfe17b64f8bfe should clarify this for others.
